### ISSUE TITLE
Fuzzy displays and sorts a list, but built-in functions do nothing

### ISSUE THREAD

**Issue by mottram** [amirrezaask/fuzzy.nvim#10]
I can only get Fuzzy to display and sort a list - none of the various builtin functions do anything.

For example, if I do `:Fuzzy find_files`, I see a list of filepaths, and typing a string will match a particular file (with matches highlighted). Hitting return when I get the match I want doesn't actually open the file, it just resets the search.

The only thing Fuzzy does is open an empty buffer, which closes when I exit Fuzzy.

I'm using Fuzzy's default settings, with `require'fuzzy'.setup {}` in `init.lua`.

nvim version: v0.5.0-dev+a129887c0

**Comment by amirrezaask** [comment]
I just created an empty config with just fuzzy and plenary and it's working, can you share your configuration ?

**Comment by mottram** [comment]
After disabling/enabling other plugins, the problem turned out to be a conflict with [Pear Tree](https://github.com/tmsvg/pear-tree) - not sure exactly what the problem is, but Fuzzy works as expected once Pear Tree is removed.

**Comment by amirrezaask** [comment]
Weird i am gonna take a look at it's source code but since it's in vimscript it's going to be hard to find the problem :)))
