### ISSUE TITLE
Buffers failing with "Buffer 99 doesn't exist"

### ISSUE THREAD

**Issue by LoricAndre** [amirrezaask/fuzzy.nvim#2]
Hi, this is the second issue I found.
I installed your plugin with vim-plug, and the `Buffers` command fails with 
```...c/.config/nvim/Plugged/fuzzy.nvim/lua/fuzzy/internal.lua:212: Vim(buffer):E86: Buffer 80 does not exist function: builtin#18 ...c/.config/nvim/Plugged/fuzzy.nvim/lua/fuzzy/internal.lua:212: Vim(buffer):E86: Buffer 99 does not exist``` in vim messages and  `zsh:99: unmatched "` in the preview window.
Tell me if I can give you more details or a log somehow.

**Comment by amirrezaask** [comment]
can you make sure that you are using latest version, the line that the error refers to is related to the fzf backend fallback that I fixed for your other issue, can you check if it's fixed ? since I can't reproduce the issue.

**Comment by LoricAndre** [comment]
It works now, but that made me notice the terminal buffers don't close, they stay in the buffer list. Should I open a new issue ?

**Comment by amirrezaask** [comment]
Can you share screenshot of the buffer list ?

**Comment by LoricAndre** [comment]
![25 10 20_11_18_48](https://user-images.githubusercontent.com/57358788/97104446-325fde00-16b4-11eb-9d4f-8345e0c1ae6d.png)

**Comment by amirrezaask** [comment]
weird you should not have those term things any more since we are not using the term buffers any more and we are using lua io.popen to get results.

**Comment by LoricAndre** [comment]
If you changed it in the last commits it might be because they are saved in my session file, I don't see them anymore after a session clear.

**Comment by amirrezaask** [comment]
The usage of term buffer is related to the other issue you had that was fixed in the latest commit.

**Comment by LoricAndre** [comment]
Perfect !
