### ISSUE TITLE
LspReferences not jumping

### ISSUE THREAD

**Issue by LoricAndre** [amirrezaask/fuzzy.nvim#7]
Basically the title, the `LspReferences` command seems to work until you select an entry, then the window closes and nothing happens (you stay on the same line).

**Comment by amirrezaask** [comment]
I have been using it for both lua and golang and it works, can you share a gif or I don't know if there is any errors ?

**Comment by LoricAndre** [comment]
Sorry for the late response, it seems it's because when you use `fzy` as fuzzy finder (I changed it directly in the code so this should not be an issue)
